
templates:
  #===========================================================================
  A4 Hochformat: !template
  #===========================================================================
    reportTemplate: a4_portrait.jrxml
    attributes:
      title: !string {}
      printScalebar: !boolean {}
      printNorthArrow: !boolean {}
      map: !map
        maxDpi: 576
        dpiSuggestions: [72,144,288,576]
        width: 535
        height: 630
      scalebar: !scalebar
        width: 240
        height: 40
        default:
          backgroundColor: "rgba(214, 214, 214, 200)"
          align: "right"
      northArrowDef: !northArrow
        size: 50
        default:
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(214, 214, 214, 200)"
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !createNorthArrow
        inputMapper: {map: map, northArrowDef: northArrow}
  #===========================================================================
  A4 Querformat: !template
  #===========================================================================
    reportTemplate: a4_landscape.jrxml
    attributes:
      title: !string {}
      printScalebar: !boolean {}
      printNorthArrow: !boolean {}
      map: !map
        maxDpi: 576
        dpiSuggestions: [72,144,288,576]
        width: 780
        height: 360
      scalebar: !scalebar
        width: 240
        height: 40
        default:
          backgroundColor: "rgba(214, 214, 214, 200)"
          align: "right"
      northArrowDef: !northArrow
        size: 50
        default:
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(214, 214, 214, 200)"
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !createNorthArrow
        inputMapper: {map: map, northArrowDef: northArrow}

